/**/callback({
  "meta": {
    "Content-Type": "application/javascript; charset=utf-8",
    "X-RateLimit-Limit": "60",
    "X-RateLimit-Remaining": "57",
    "X-RateLimit-Reset": "1480430660",
    "Cache-Control": "public, max-age=60, s-maxage=60",
    "Vary": "Accept",
    "ETag": "\"2880c37d2f3aea43249cbca4dcd93b6d\"",
    "Last-Modified": "Wed, 23 Nov 2016 21:26:42 GMT",
    "X-GitHub-Media-Type": "github.v3",
    "status": 200
  },
  "data": {
    "login": "kennethreitz",
    "id": 119893,
    "avatar_url": "https://avatars.githubusercontent.com/u/119893?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kennethreitz",
    "html_url": "https://github.com/kennethreitz",
    "followers_url": "https://api.github.com/users/kennethreitz/followers",
    "following_url": "https://api.github.com/users/kennethreitz/following{/other_user}",
    "gists_url": "https://api.github.com/users/kennethreitz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kennethreitz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kennethreitz/subscriptions",
    "organizations_url": "https://api.github.com/users/kennethreitz/orgs",
    "repos_url": "https://api.github.com/users/kennethreitz/repos",
    "events_url": "https://api.github.com/users/kennethreitz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kennethreitz/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Kenneth Reitz",
    "company": "Heroku",
    "blog": "http://kennethreitz.org",
    "location": "Winchester, VA",
    "email": "me@kennethreitz.org",
    "hireable": true,
    "bio": "I wrote Requests: HTTP for Humans. The only thing I really care about is interface design. ",
    "public_repos": 94,
    "public_gists": 210,
    "followers": 12376,
    "following": 193,
    "created_at": "2009-08-26T21:17:47Z",
    "updated_at": "2016-11-23T21:26:42Z"
  }
})
